if (self.CavalryLogger) { CavalryLogger.start_js(["bAtiNNY"]); }

__d("MWChatBusinessCTAAdsSenderMutation.graphql",[],(function(a,b,c,d,e,f){"use strict";a=function(){var a=[{defaultValue:null,kind:"LocalArgument",name:"input"}],b=[{alias:null,args:[{kind:"Variable",name:"action_link",variableName:"input"}],kind:"ScalarField",name:"messenger_business_ads_sender",storageKey:null}];return{fragment:{argumentDefinitions:a,kind:"Fragment",metadata:null,name:"MWChatBusinessCTAAdsSenderMutation",selections:b,type:"Mutation",abstractKey:null},kind:"Request",operation:{argumentDefinitions:a,kind:"Operation",name:"MWChatBusinessCTAAdsSenderMutation",selections:b},params:{id:"3559873240789162",metadata:{},name:"MWChatBusinessCTAAdsSenderMutation",operationKind:"mutation",text:null}}}();e.exports=a}),null);
__d("NullStateLists",["IconSource"],(function(a,b,c,d,e,f,g){"use strict";a={dark:new(c("IconSource"))("nullStateGlyphs","/images/comet/empty_states_icons/lists/null_states_list_dark_mode.svg",112),"default":new(c("IconSource"))("nullStateGlyphs","/images/comet/empty_states_icons/lists/null_states_list_gray_wash.svg",112)};g["default"]=a}),98);
__d("MarketplacePDPRHCUnit.hybrid",["react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react");function a(a){var b=a.content,c=a.testid;c=a.title;return h.jsxs("div",{className:"n851cfcs","data-testid":void 0,children:[c,h.jsx("div",{className:"aahdfvyu","data-testid":void 0,children:b})]})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("MWChatBusinessCTAAdsSenderMutation",["CometRelay","MWChatBusinessCTAAdsSenderMutation.graphql"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h!==void 0?h:h=b("MWChatBusinessCTAAdsSenderMutation.graphql");function a(a,b){d("CometRelay").commitMutation(a,{mutation:i,onCompleted:function(){},onError:function(a){},variables:{input:b}})}g.sendAds=a}),98);
__d("createUseMutation_DEPRECATED",["CometRelay","Promise","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useCallback;function a(a,c,e,f){return function(){var g=d("CometRelay").useRelayEnvironment();return h(function(h,i,j){return new(b("Promise"))(function(b,k){return d("CometRelay").enqueueMutation(g,{mutation:a,onCompleted:function(a,c){c&&c.length?k(c):b(a)},onError:function(a){return k([a])},optimisticResponse:c?c(h,i,j):null,optimisticUpdater:e?e(h,i,j):null,updater:f?f(h,i,j):null,variables:babelHelpers["extends"]({input:h},i)})})},[g])}}g["default"]=a}),98);
__d("CometSaveLoggingContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b=a.createContext({collectionID:null,referrer:null,surface:"dashboard",surfaceGraphQL:"DASHBOARD",surfaceGraphQL_legacy:"dashboard"});g["default"]=b}),98);
__d("useCometSaveLoggingContext",["CometSaveLoggingContext","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useContext;function a(){return h(c("CometSaveLoggingContext"))}g["default"]=a}),98);
__d("CometSaveStoryMutationHelper",[],(function(a,b,c,d,e,f){"use strict";function a(a,b,c){b&&b.forEach(function(b){b=a.get(b);if(b!=null){b=b.getLinkedRecord("save_info");b!=null&&b.setValue(c,"viewer_save_state")}})}function b(a,b,c){b&&b.forEach(function(b){b=a.get(b);b!=null&&b.setValue(c,"viewer_saved_state")})}f.updateStoriesSaveState=a;f.updateSavablesSaveState=b}),66);
__d("useSaveMutation",["JSResourceForInteraction","promiseDone","react","unrecoverableViolation","useCometSaveLoggingContext"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useCallback,i=c("JSResourceForInteraction")("CometSaveMutation").__setRef("useSaveMutation");function a(a,b){var d=a.mechanism,e=a.savableID;a=a.surface;var f=c("useCometSaveLoggingContext")().surfaceGraphQL_legacy,g=(a=a)!=null?a:f;a=b||{};var j=a.onFailure,k=a.onSuccess;return h(function(){if(e==null)throw c("unrecoverableViolation")("savableID not provided to save mutation","saved_for_later");c("promiseDone")(i.load().then(function(a){a({mechanism:d,node_id:e,surface:g},{onFailure:j,onSuccess:k})}))},[d,e,g,k,j])}g["default"]=a}),98);
__d("useUnsaveMutation",["JSResourceForInteraction","promiseDone","react","unrecoverableViolation","useCometSaveLoggingContext"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useCallback,i=c("JSResourceForInteraction")("CometUnsaveMutation").__setRef("useUnsaveMutation");function a(a,b){var d=a.mechanism,e=a.savableID;a=a.surface;var f=c("useCometSaveLoggingContext")().surfaceGraphQL_legacy,g=(a=a)!=null?a:f;a=b||{};var j=a.onFailure,k=a.onSuccess;return h(function(){if(e==null)throw c("unrecoverableViolation")("savableID not provided to unsave mutation","saved_for_later");c("promiseDone")(i.load().then(function(a){a({mechanism:d,node_id:e,surface:g},{onFailure:j,onSuccess:k})}))},[e,d,g,j,k])}g["default"]=a}),98);
__d("XCometSaveDashboardControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/saved/",Object.freeze({unlisted_only:!1}),void 0);b=a;g["default"]=b}),98);
__d("CometSaveToastUtil",["fbt","CometLink.react","XCometSaveDashboardControllerRouteBuilder","react"],(function(a,b,c,d,e,f,g,h){"use strict";var i=d("react");function a(a,b,d){d=(d=d)!=null?d:a!==null?c("XCometSaveDashboardControllerRouteBuilder").buildURL({list_id:a}):null;return b!=null?h._("Saved to {=[Name of collection]}",[h._param("=[Name of collection]",i.jsx(c("CometLink.react"),{href:d,children:h._("{Name of collection}",[h._param("Name of collection",i.jsx("b",{children:b}))])}))]):h._("Added to collection")}g.getAddToCollectionToast=a}),98);