if (self.CavalryLogger) { CavalryLogger.start_js(["XsIDPDJ"]); }

__d("CometSinglePageChannelTabRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"4454961011209197",metadata:{},name:"CometSinglePageChannelTabRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometTahoeRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"6361353240571925",metadata:{},name:"CometTahoeRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideosLoggedOutCTAWrapperFooterDataQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3376330692474027",metadata:{},name:"CometVideosLoggedOutCTAWrapperFooterDataQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomePlaylistRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"5829817123755503",metadata:{},name:"CometVideoHomePlaylistRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomeRootProviderQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"2939812456104778",metadata:{},name:"CometVideoHomeRootProviderQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomeStickyHeaderWatchlistMenuRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3707683145972691",metadata:{},name:"CometVideoHomeStickyHeaderWatchlistMenuRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomeLeftRailWatchlistQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"5956495877755568",metadata:{},name:"CometVideoHomeLeftRailWatchlistQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometSinglePageChannelTabRoot.entrypoint",["CometSinglePageChannelTabRootQuery$Parameters","JSResourceForInteraction","WebPixelRatio","buildCometSinglePageRoute.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";a=c("buildCometSinglePageRoute.entrypoint")(c("JSResourceForInteraction")("CometSinglePageChannelTabRoot.react").__setRef("CometSinglePageChannelTabRoot.entrypoint"),function(a){a=a.routeProps.pageID;return{queries:{singlePageChannelTabRootQueryReference:{parameters:b("CometSinglePageChannelTabRootQuery$Parameters"),variables:{UFI2CommentsProvider_commentsKey:"CometSinglePageChannelTabRoot",displayCommentsContextEnableComment:null,displayCommentsContextIsAdPreview:null,displayCommentsContextIsAggregatedShare:null,displayCommentsContextIsStorySet:null,displayCommentsFeedbackContext:null,feedLocation:"PAGE_TIMELINE",feedbackSource:72,focusCommentID:null,pageID:a,scale:d("WebPixelRatio").get()*4,showReactions:!0,useDefaultActor:!1}}}}});g["default"]=a}),98);
__d("validateChainingCaller",[],(function(a,b,c,d,e,f){"use strict";function a(a){return typeof a==="string"?a:null}f["default"]=a}),66);
__d("validateChannelEntryPoint",[],(function(a,b,c,d,e,f){"use strict";function a(a){return typeof a==="string"?a:null}f["default"]=a}),66);
__d("CometTahoeRoot.entrypoint",["CometTahoeRootQuery$Parameters","CometVideosLoggedOutCTAWrapperFooterDataQuery$Parameters","JSResourceForInteraction","WebPixelRatio","gkx","validateChainingCaller","validateChannelEntryPoint"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){var b=a.routeParams.story_token,e=a.passthroughProps,f=(e==null?void 0:e.playerOrigin)!=null?String(e==null?void 0:e.playerOrigin):void 0,g=(e==null?void 0:e.playerSuborigin)!=null?String(e==null?void 0:e.playerSuborigin):void 0,h=(e==null?void 0:e.channelID)!=null?String(e==null?void 0:e.channelID):null,i=c("validateChainingCaller")(e==null?void 0:e.caller),j=c("validateChannelEntryPoint")(e==null?void 0:e.channelEntryPoint),k=null;(e==null?void 0:e.searchKeyword)!=null&&(k=JSON.stringify({searchKeyword:e==null?void 0:e.searchKeyword}));var l=(e==null?void 0:e.chainingCursor)!=null?String(e==null?void 0:e.chainingCursor):null;e=(e==null?void 0:e.chainingSeedVideoId)!=null?String(e==null?void 0:e.chainingSeedVideoId):null;e={UFI2CommentsProvider_commentsKey:"CometTahoeSidePaneQuery",caller:(i=i)!=null?i:"TAHOE",chainingCursor:l,chainingSeedVideoId:e,channelEntryPoint:(i=j)!=null?i:"TAHOE",channelID:(l=h)!=null?l:"",displayCommentsContextEnableComment:null,displayCommentsContextIsAdPreview:null,displayCommentsContextIsAggregatedShare:null,displayCommentsContextIsStorySet:null,displayCommentsFeedbackContext:null,feedLocation:"TAHOE",feedbackSource:41,focusCommentID:null,privacySelectorRenderLocation:"COMET_STREAM",renderLocation:"video_channel",scale:d("WebPixelRatio").get(),useDefaultActor:!1,videoChainingContext:k};j=babelHelpers["extends"]({},e,{playerOrigin:f,playerSuborigin:g});i={tahoeRootQueryReference:{parameters:c("CometTahoeRootQuery$Parameters"),variables:babelHelpers["extends"]({},j,{videoID:b})}};c("gkx")("1801392")&&(i=babelHelpers["extends"]({},i,{loggedOutCTAfooterDataQueryReference:{parameters:c("CometVideosLoggedOutCTAWrapperFooterDataQuery$Parameters"),variables:{nodeID:b,scale:d("WebPixelRatio").get()}}}));return{extraProps:{t:a.routeProps.t},queries:i}},root:c("JSResourceForInteraction")("CometTahoeRoot.react").__setRef("CometTahoeRoot.entrypoint")};g["default"]=a}),98);
__d("buildCometVideoHomeRouteForResource.entrypoint",["CometVideoHomeLeftRailWatchlistQuery$Parameters","CometVideoHomeRootProviderQuery$Parameters","CometVideoHomeStickyHeaderWatchlistMenuRootQuery$Parameters","WebPixelRatio","cr:1714517","createContentAreaCompoundEntryPointBuilder"],(function(a,b,c,d,e,f,g){"use strict";b("cr:1714517");function a(a){return c("createContentAreaCompoundEntryPointBuilder")(a,function(a){return{rootProviderQueryReference:{parameters:b("CometVideoHomeRootProviderQuery$Parameters"),variables:{}},stickyHeaderWatchlistQueryReference:{parameters:b("CometVideoHomeStickyHeaderWatchlistMenuRootQuery$Parameters"),variables:{scale:d("WebPixelRatio").get()}},watchlistSettingsQueryReference:{parameters:b("CometVideoHomeLeftRailWatchlistQuery$Parameters"),variables:{scale:d("WebPixelRatio").get()}}}})}g["default"]=a}),98);
__d("buildCometVideoHomeRoute.entrypoint",["JSResourceForInteraction","buildCometVideoHomeRouteForResource.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";a=c("buildCometVideoHomeRouteForResource.entrypoint")(c("JSResourceForInteraction")("CometVideoHomeRoot.react").__setRef("buildCometVideoHomeRoute.entrypoint"));g["default"]=a}),98);
__d("CometVideoHomePlaylistRoot.entrypoint",["CometVideoHomePlaylistRootQuery$Parameters","JSResourceForInteraction","WebPixelRatio","buildCometVideoHomeRoute.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";a=c("buildCometVideoHomeRoute.entrypoint")(c("JSResourceForInteraction")("CometVideoHomePlaylistRoot.react").__setRef("CometVideoHomePlaylistRoot.entrypoint"),function(a){a={id:a.routeProps.id};return{queries:{playlistRootQueryReference:{parameters:b("CometVideoHomePlaylistRootQuery$Parameters"),variables:{scale:d("WebPixelRatio").get(),trigger_data:a}}}}});g["default"]=a}),98);
__d("CometVideoHomeRootBEOneAhead",["JSResourceForInteraction"],(function(a,b,c,d,e,f,g){"use strict";c("JSResourceForInteraction")("CometVideoHomeRoot.react").__setRef("CometVideoHomeRootBEOneAhead");a=null;g["default"]=a}),98);
__d("CometVideoHomeLanceletRoot.entrypoint",["CometSinglePageChannelTabRoot.entrypoint","JSResourceForInteraction","buildCometVideoHomeRoute.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";a=c("buildCometVideoHomeRoute.entrypoint")(c("JSResourceForInteraction")("CometVideoHomeLanceletRoot.react").__setRef("CometVideoHomeLanceletRoot.entrypoint"),function(a){return{entryPoints:{pageEntryPoint:{entryPoint:b("CometSinglePageChannelTabRoot.entrypoint"),entryPointParams:a}},extraProps:a}});g["default"]=a}),98);